### ISSUE TITLE
Propagate `errno` for proper error messages

### ISSUE THREAD

**Issue by nh2** [asmaloney/libE57Format#101]
I'm using `libE57Format` through [pye57](https://github.com/davidcaron/pye57) and noticed that `E57_ERROR_OPEN_FAILED` is raised for any error, including standard cases such as:

* `no such file or directory`
* `permission denied`
* `too many open files`

Most software can point out these error reasons by consulting `errno` (e.g. via `strerror()`), or at least guaranteeing in the API docs to not mess with `errno` so that the caller can inspect `errno` themselves.

It would be great if `libE57Format` could do one of these so that users can get much better error messages along with `E57_ERROR_OPEN_FAILED`.

**Comment by asmaloney** [comment]
I'm not sure I can guarantee the state of `errno`, but what I can do is provide the errno & string in the exception context.

So instead of:
```
result=-1 fileName=./no-path/foo.e57 flags=1538 mode=438
```

We'd have:

```
errno=2 error='No such file or directory' fileName=./no-path/foo.e57 flags=1538 mode=438
```

I don't know what pye57 does with the exception context, but would this solve your issue?

**Comment by nh2** [comment]
Yes, that would solve the issue!
