### ISSUE TITLE
Propose we move to C++14

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/libE57Format#109]
Does anyone using this library have any strong opinions about moving the required C++ version to [C++14](https://en.cppreference.com/w/cpp/14)?

I want to use [[[deprecated]]](https://en.cppreference.com/w/cpp/language/attributes/deprecated). There are funky macro headers to try to do this in a cross-platform way, but they are total hacks.

I'd even be happy to require C++17 to get access to [std::filesystem](https://en.cppreference.com/w/cpp/filesystem), but maybe that's a bit of a stretch?

**Comment by dgirardeau** [comment]
I'm good with C++14 (and even C++ 17). Thanks for asking ;)

**Comment by nigels-com** [comment]
C++14 would be fine for our purposes, but I'm not sure we're ready for C++17.

**Comment by asmaloney** [comment]
I've heard from a few people now and the consensus is that the move to C++14 is fine. As expected, it's probably too early for C++17.

So my plan is to release 2.3.0, then master will become 3.0 and require C++14. Anyone requiring C++11 can still use the 2.x branch and they can backport things if they need to.
