### ISSUE TITLE
Stream Input

### ISSUE THREAD

**Issue by jean-noelp** [asmaloney/libE57Format#15]
Hello,

I think it could be very nice to have a stream input mode, instead of file only !
i.e. something like ImageFile(&stream) + CheckedStream(const char*).

What do you think ?

**Comment by asmaloney** [comment]
I'm certainly not opposed if there's a good reason for it.

Do you have a use-case in mind?

**Comment by jean-noelp** [comment]
Yes, I'm working on a web-service which transforms many file formats in other formats, and E57 takes part of this.
I will do some tests, and if it's relevant, I will prupose a PR, maybe.

**Comment by asmaloney** [comment]
Sounds good.

I'm not sure how large a change this would be, but please note that I will not accept large pull requests (>150 lines-ish _unless absolutely necessary_). So it will have to be submitted in small, logical, working, and understandable PRs.

(General rule of thumb - if it takes a reviewer more than 5-10 minutes to review, it's probably too big.)

Thanks!

**Comment by jean-noelp** [comment]
All right.
Normally it consists of a new stream like file stream, and some checks between these two streams.

**Comment by asmaloney** [comment]
I'm not sure how familiar you are with E57, but it's an odd format. Given the layout of the data and the spec for the format, I'm not sure how streaming is going to work. Maybe you could outline that for me?

It might help crystallize your plan and would help me understand better what you're proposing.

**Comment by asmaloney** [comment]
How does your tool work?

User selects a local file, it is streamed to your server, and the backend decodes and re-encodes it to a different format?

If so, this is going to be problematic for the E57 format. The layout of a file is as follows:

1. header (fixed length)
2. variable format binary data (variable length)
3. index/format details as XML (variable length)

So in order to understand the binary data (2), you need to read, parse, and manipulate the XML data from (3) first.

Unless you have a plan to do some processing locally?

**Comment by jean-noelp** [comment]
In fact, the file is already read into a char* (in Rust language) before any call to libE57Format (in C++). So libE57Format juste need to manage a char* buffer instead of a file.

**Comment by asmaloney** [comment]
Ah - now I understand.

Yes, memory is a serious issue with these files. I have one 17 GB file that is a pathological case :-)

**Comment by jean-noelp** [comment]
Normally the PR should work, but I had some manual merge at home, so you have to be careful with this! ^^"
Positive point: I think i have successfully used buffer reading with full memory optimizations.
