### ISSUE TITLE
question: what is the "clip" parameter of PC ?

### ISSUE THREAD

**Issue by jean-noelp** [asmaloney/libE57Format#20]
Hello (again),

I would like to know what is the label of the specific parameter in header that is supposed to "clip" the point cloud ?

Because on [this scan](http://sourceforge.net/projects/e57-3d-imgfmt/files/E57Example-data/manitou.e57/download), I have loooot of data more than in CloudCompare with the same file.

**Comment by asmaloney** [comment]
The header for an E57 file is very small (48 bytes) and only contains the following:

- file signature
- version info
- file length
- xml offset
- xml length
- page size

There's nothing in the file format about clipping that I'm aware of.

Looking at the data for that file, there should be 5 scans for a total of 4,122,591 points and 5 2D images.

What are you getting from it (both your work and CloudCompare's)?

**Comment by jean-noelp** [comment]
Yep, not the right way also...

I have this huge point cloud (please do not care about debugging color):

Zoom 1:
![Capture d’écran 2019-05-28 à 17 32 46](https://user-images.githubusercontent.com/28710922/58491215-e7643300-816e-11e9-8b1c-ae8323bb0510.png)
Zoom 2:
![Capture d’écran 2019-05-28 à 17 32 52](https://user-images.githubusercontent.com/28710922/58491235-ecc17d80-816e-11e9-9fe6-28cc615329e3.png)
Zoom 3:
![Capture d’écran 2019-05-28 à 17 33 01](https://user-images.githubusercontent.com/28710922/58491255-f34ff500-816e-11e9-9959-0330e6b224f8.png)

But in CloudCompare there is just this section:
![Capture d’écran 2019-05-28 à 17 33 12](https://user-images.githubusercontent.com/28710922/58491282-006ce400-816f-11e9-9980-45da9e317e83.png)

Both contains 5 groups.

**Comment by asmaloney** [comment]
Oh - you probably aren't ignoring invalid points.

There is a field in the points prototype called `cartesianInvalidState` that will tell you whether the point is valid or not. (It's actually more complicated than that - 0 means all the cartesian point data is valid, 1 means it's partially valid, and 2 means it's invalid.)

(I would also suggest getting a copy of the [actual E57 standard](https://www.astm.org/Standards/E2807.htm) since the code in this library is quite difficult to understand.)

**Comment by jean-noelp** [comment]
Okay, this parameter `cartesianInvalidState` does not look like easy to understand indeed,
I will make some research about it...

Thank you!

**Comment by asmaloney** [comment]
> this parameter cartesianInvalidState does not look like easy to understand indeed

The whole format is like this :-)

Other optional fields in the point prototype you will have to consider: `sphericalInvalidState`, `isTimeStampInvalid`, `isIntensityInvalid`, and `isColorInvalid`.

There are some design decisions that were made when they created this format that make it difficult to work with which is probably why we don't have other open source implementations of it.
