### ISSUE TITLE
Any simple example on how to write e57 format using raw 3d laser scan data

### ISSUE THREAD

**Issue by shubhamwagh** [asmaloney/libE57Format#21]
Hi!
I have a laser scanner which rotates 360 degree to create 3d scans. Currently I use PCL and save it in the form of unorganized point cloud and save the scan in PCD format.

I actually want to get a structured 3D scan in the form of e57 file format for which I also have the corresponding raw images and raw laserscan data saved whilst scanning for every rotation angle(so structure is still preserved as the raw data is collected). 

May I know if there is any simple example on how to write e57 file format from raw laser scan data? Thanks

**Comment by asmaloney** [comment]
For general examples of using this library to write files, you might look at the [E57 Simple API](http://libe57.org/download.html). It provides a higher-level API for working with E57 files using the original version of this library (E57RefImpl - also available through that link).

**Comment by dogod621** [comment]
Here is a simple interface for PCD->E57 and E57->PCD(single scan):
https://github.com/madduci/PCD-E57

beware, he didnot read scaled integer XYZ correctly :
for correctly read scaled integer, please read this issue: https://github.com/asmaloney/libE57Format/issues/16

**Comment by shubhamwagh** [comment]
@dogod621  thanks for the link, I think that will precisely help. Even though the conversion still have unstructured scan, but that will certainly help with something to start with.

**Comment by smileymoody** [comment]
@shubhamwagh Have you had any success in converting an unstructured scan to a structured one?

I also have a 360 Lidar (Velodyne VLP-16), I use MATLAB to extract point cloud and save them as .ply. I tried to use CloudCompare to convert files to .e57, but RC (Reality Capture) still failed to import.

Any advice is greatly appreciated.
