### ISSUE TITLE
Catch `e57::E57Exception` exceptions in tests

### ISSUE THREAD

**Issue by marxin** [asmaloney/libE57Format#255]
I'm trying to update the project to Conan package and it seems the MacOS tests fail:
[libe57format-macos.txt](https://github.com/asmaloney/libE57Format/files/12342066/libe57format-macos.txt)

Can you please catch the aforementioned exception so that we can debug it?

**Comment by asmaloney** [comment]
I'm not sure what you're asking for here. `test_package` isn't part of libE57Format.

**Comment by marxin** [comment]
You're right, it's a smoke test that lives in Conan repository.

**Comment by asmaloney** [comment]
There is a [test suite](https://github.com/asmaloney/libE57Format/tree/master/test) for the library - it should probably run that?
