### ISSUE TITLE
missing header for std integer types

### ISSUE THREAD

**Issue by christianrauch** [asmaloney/libE57Format#269]
I am getting compilation errors for version 2.3 such as `error: ‘int16_t’ has not been declared in ‘std’`. According to https://en.cppreference.com/w/cpp/types/integer, the header `cstdint` is missing.

**Comment by asmaloney** [comment]
Which compiler/OS are you using?

What file is the error in?

Is it an error with 3.1.0?

**Comment by christianrauch** [comment]
It's `E57Format.h` version 2.3. The error actually occurs in the CloudCompare flatpak: https://buildbot.flathub.org/#/builders/37/builds/10328/steps/8/logs/stdio.

**Comment by asmaloney** [comment]
That header is included in [the latest version](https://github.com/asmaloney/libE57Format/blob/04c0c097928c2b0b807443aad41da63100661df5/include/E57Format.h#L35C7-L35C7).

I guess they'll have to update then? Not much I can do from here!

**Comment by dgirardeau** [comment]
Good idea: https://github.com/CloudCompare/CloudCompare/pull/1892
