### ISSUE TITLE
Failing with uint8_t has not been declared in std

### ISSUE THREAD

**Issue by hadjiprocopis** [asmaloney/libE57Format#310]
```
E57Format.h:50:15: error: ‘uint8_t’ has not been declared in ‘std’
   50 |    using std::uint8_t;
```
etc.

One solution is to add ```#include <cstdint>``` in file ```include/E57Format.h```.
thanks for the free software!

**Comment by bhomaidan1990** [comment]
@hadjiprocopis do you have [this line](https://github.com/asmaloney/libE57Format/blob/master/include/E57Format.h#L35)?

**Comment by hadjiprocopis** [comment]
No, the *vesrion I had* (v2.3.0) did not have that line. But that was a 
3rdparty dependency of (latest) Meshlab. And now I checked it is quite 
an older version than your current.

It looks the problem has been solved with current version of
libE57Format.

Apologies for the false alarm.

thank you.
