### ISSUE TITLE
SimpleAPI and SYSTEMTIME identifier Unidentified

### ISSUE THREAD

**Issue by cwzelus** [asmaloney/libE57Format#37]
First I want to apologize if this is a horrible place to ask this. However I am working with the source code from libE57 and the project compiled up to the Foundation API. I seem to have major difficulties when adding in the Simple API with their instructions. I am getting a lot of identifiers undefined . One of the first ones to show unidentified is "SYSTEMTIME". I am curious if you could give some tips on how to properly add in the Simple API source...

**Comment by asmaloney** [comment]
> First I want to apologize if this is a horrible place to ask this.

No problem at all.

> I am working with the source code from libE57

Are you trying to use the code from this repo ([libE57Format](https://github.com/asmaloney/libE57Format)) or from the reference implementation on SourceForge ([E57RefImpl](https://sourceforge.net/projects/e57-3d-imgfmt/))?

Either way I haven't looked at the "Simple" files, but if you're using libE57Format and can give more information (what compiler, what OS, the actual errors your getting), I might be able to see if it's something I changed in the API.

**Comment by cwzelus** [comment]
I am working with the Foundation API for the E57RefImpl at the moment. I was hoping the Simple API would help solve some of the challenges I was facing. After working with the API, i guess Im looking more for advice on how to pursue the effect I am looking for. 

I have 2 E57 files. One is the "Original" file. This contains imagery and colored data and works in all platforms tested (recap, scene, cloudcompare, cyclone, etc.)

Then I have a second file, "Modified" that is exported from CloudCompare. However this file has issues with Intensity scaling as well as the images that are used for bubble views resulting in other platforms being unable to display the bubble views. The only platform that seems to still be able to display bubble views is Cyclone on this file. 

So my intention is to create a third file "Frankenstein", that takes whatever changes were applied to "Modified" and inject the corresponding pieces of remaining elements/nodes from "Original" to create a third file that has the modifications but keeps the correct structure and parameters to still display the bubble views properly and display the intensity at a visually appealing scale. 

Would you have any thoughts on how to pursue this? In particular, thoughts on how to obtain the imagery data/components from the "Original" file and apply them to "Frankenstein"?

**Comment by asmaloney** [comment]
> However this file has issues with Intensity scaling as well as the images that are used for bubble views resulting in other platforms being unable to display the bubble views.

Isn't this a bug with CloudCompare's E57 support then? i.e. if it's fixable in CloudCompare would it alleviate the need for your "Frankenstein" workaround?

Just wondering if it makes more sense to try to fix the issue in CloudCompare rather than work around it with an extra tool.

**Comment by dgirardeau** [comment]
I think a 'clean' solution would be to save all the data / pieces of information that are not managed by CloudCompare as 'meta-data' attached to the loaded cloud(s). Then when the cloud is exported back to E57, process all the pieces of meta-data and write them to the file.

However it might be a huge work, I'm not sure.

**Comment by asmaloney** [comment]
@cwzelus If you decide to go with creating your tool, [this PR](https://github.com/asmaloney/libE57Format/pull/41) from @ptc-jhoerner might be of interest.

He is bringing the "Simple" API from the old ref implementation to libE57Format.

**Comment by asmaloney** [comment]
@cwzelus The "Simple API" has been added this library. That might help your work.

I would still suggest that if CloudCompare is producing E57 files that are not valid or not working in other software, then that should be reported as a [CloudCompare issue](https://github.com/CloudCompare/CloudCompare/issues) with a sample file and steps to reproduce so it can be looked at there.

Please feel free to re-open this issue if you want to continue the conversation.
