### ISSUE TITLE
Exception when using Reader.SetUpData3DPointsData

### ISSUE THREAD

**Issue by d3m14w** [asmaloney/libE57Format#51]
Hello,

I'm having problem using Reader.SetUpData3DPointsData included from E57SimpleReader.

Here is my simple code :
```
#include <iostream>
#include "E57SimpleReader.h"
#include "E57SimpleData.h"
#include "E57Exception.h"

using namespace std;
using namespace e57;

int main() {
    Reader reader("bunnyDouble.e57");
    E57Root fileHeader;
    Data3D data3DHeader;
    Data3DPointsData buffers;

    reader.GetE57Root(fileHeader);
    cout << "FormatName : " << fileHeader.formatName << endl;
    cout << "e57LibraryVersion : " << fileHeader.e57LibraryVersion << endl;
    cout << "data3DSize : " << fileHeader.data3DSize << endl;
    
    reader.ReadData3D(0, data3DHeader);
    cout << "name : " << data3DHeader.name << endl;
    
    if (reader.IsOpen()) {
        cout << "Open" << endl;
        try {
            cout << "Here A " << endl;
            CompressedVectorReader dataReader = reader.SetUpData3DPointsData (0, 2, buffers);
            cout << "Here B" << endl;
        } catch (E57Exception &e) {
            cout << "exception caught in (" << e.context() << "): " << Utilities::errorCodeToString(e.errorCode()) << '\n';
        }
    } else
        cout << "Close" << endl;

    return 0;
}
```

And here is the output :
```
FormatName : ASTM E57 3D Imaging Data File
e57LibraryVersion : InteliSum-LD3-Studio-V5.1-E57RefImpl-1.0.154-x86-windows
data3DSize : 1
name : bunny
Open
Here A 
exception caught in (fileName=bunnyDouble.e57): bad API function argument provided by user (E57_ERROR_BAD_API_ARGUMENT)
```

Honestly, I don't know what went wrong. Everything seems fine.

If I trace the line that throw the exception, I guess the line that throw the exception is in E57FormatImpl.cpp, line 486-490 :
```
/// dbufs can't be empty
   if ( dbufs.empty() )
   {
      throw E57_EXCEPTION2( E57_ERROR_BAD_API_ARGUMENT, "fileName=" + destImageFile->fileName() );
   }
```
Should the buffer initialized first? How?
A correct example of usage is apreciated.

Note: I'm a C++ newbie. But have a little experience in Java. So please don't bully me if somehow I made an elementary mistake.

**Comment by asmaloney** [comment]
> Should the buffer initialized first? How?

Yes - it seems that `Data3DPointsData` is a bunch of pointers to buffers that you are supposed to allocate. Since you aren't doing so, it gives an error because there's nothing to do. It looks like it needs `count` space (in your example, "2") for each item.

My guess is that if you just want the (x, y, z), for example, you would allocate space for those in `buffers` (cartesianX, cartesianY, cartesianZ) and the data will be filled in. Something like:

```cpp
const int cBufferSize = 2;

buffers.cartesianX = new float[cBufferSize];
buffers.cartesianY = new float[cBufferSize];
buffers.cartesianZ = new float[cBufferSize];
```

(Don't forget to `delete` the pointers when you're done with them.)

@ptc-jhoerner Would know more about this than I do and can correct me if I'm wrong.

**Comment by d3m14w** [comment]
I see, it's all settled now. The code run without exception.

It seems I did make elementary mistake.

Thank you so much
