### ISSUE TITLE
Build instructions on Windows 10 with Visual Studio 2019

### ISSUE THREAD

**Issue by dawiddyrcz** [asmaloney/libE57Format#64]
Hello, 
I've made a instruction how to build this library it with xerces library on windows. I've made this because I lost some time on that. I am a c# developer and building things in c++ is not obvious for me. Maybe it will help someone

**Instruction include building xerces-c and libE57Format.**

Open command prompt (I am using git bash).

1. Firstly clone and build xerces-c:

```
git clone --depth 1 --branch v3.2.3 https://github.com/apache/xerces-c.git
cd xerces-c
mkdir build
cd build
cmake ..
cmake --build . --config Debug --target install
cd ..
cd ..
```
2. Secondly clone the libE57Format:

```
git clone https://github.com/asmaloney/libE57Format.git
cd libE57Format
```

![Folder](https://user-images.githubusercontent.com/34553866/104463246-d2414f80-55b1-11eb-8846-58b249cc3ee5.png)

3. And now is a tricky situation because cmake don't know where is the xerces-c library. You should open **CMakeLists.txt** (which is in the **libE57Format** directory )
and before **find_package( XercesC REQUIRED )** add:

```
set ( XercesC_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/../xerces-c/src/" "${CMAKE_SOURCE_DIR}/../xerces-c/build/src/")
set ( XercesC_LIBRARY "${CMAKE_SOURCE_DIR}/../xerces-c/build/src/Debug/")
set ( XercesC_VERSION "3.2.3")
```

![CMakeLists txt change](https://user-images.githubusercontent.com/34553866/104462785-46c7be80-55b1-11eb-86ad-f0999b08e6ca.png)

4. After that come back to command prompt and type:

```
mkdir build
cd build
cmake ..
cmake --build . --config Debug
```

5. Concratulation you have build library. 

Now you have to add to your new project:
**E57Format-d.lib**  from **libE57Format\build\Debug** to libraries
**xerces-c_3D.lib** from **xerces-c\build\src\Debug** to libraries 
**xerces-c_3_2D.dll**  copy to output folder

And **add all "*.h" files** from folder **libE57Format\include**
And add include file **E57Export.h** from **libE57Format\build**

**Comment by asmaloney** [comment]
Thanks Dawid.

I would offer a correction though. In step 3 you are modifying libE57Format's cmake file. This is not the proper way to use cmake.

You should pass the options on the command line in step 4. You would do something like:

```sh
mkdir build
cd build
cmake \
    -DXercesC_INCLUDE_DIR:PATH=/path/to/xerces/include \
    -DXercesC_LIBRARY:PATH=/path/to/xerces/lib/libxerces-c.dll \
    ..
cmake --build . --config Debug
```

(Note: you shouldn't be setting `XercesC_VERSION`).

Whenever I have to do something like this outside my application's build setup, I write a small shell script to do it so it eliminates typos & errors and makes it easy to create reproducible builds.

**Comment by dawiddyrcz** [comment]
Thank, you for suggestion but i tried it before post my solution. It doesn't work.

**Comment by mohd-naushaaad** [comment]
> Hello,
> I've made a instruction how to build this library it with xerces library on windows. I've made this because I lost some time on that. I am a c# developer and building things in c++ is not obvious for me. Maybe it will help someone
> 
> **Instruction include building xerces-c and libE57Format.**
> 
> Open command prompt (I am using git bash).
> 
> 1. Firstly clone and build xerces-c:
> 
> ```
> git clone --depth 1 --branch v3.2.3 https://github.com/apache/xerces-c.git
> cd xerces-c
> mkdir build
> cd build
> cmake ..
> cmake --build . --config Debug --target install
> cd ..
> cd ..
> ```
> 
> 1. Secondly clone the libE57Format:
> 
> ```
> git clone https://github.com/asmaloney/libE57Format.git
> cd libE57Format
> ```
> 
> ![Folder](https://user-images.githubusercontent.com/34553866/104463246-d2414f80-55b1-11eb-8846-58b249cc3ee5.png)
> 
> 1. And now is a tricky situation because cmake don't know where is the xerces-c library. You should open **CMakeLists.txt** (which is in the **libE57Format** directory )
>    and before **find_package( XercesC REQUIRED )** add:
> 
> ```
> set ( XercesC_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/../xerces-c/src/" "${CMAKE_SOURCE_DIR}/../xerces-c/build/src/")
> set ( XercesC_LIBRARY "${CMAKE_SOURCE_DIR}/../xerces-c/build/src/Debug/")
> set ( XercesC_VERSION "3.2.3")
> ```
> 
> ![CMakeLists txt change](https://user-images.githubusercontent.com/34553866/104462785-46c7be80-55b1-11eb-86ad-f0999b08e6ca.png)
> 
> 1. After that come back to command prompt and type:
> 
> ```
> mkdir build
> cd build
> cmake ..
> cmake --build . --config Debug
> ```
> 
> 1. Concratulation you have build library.
> 
> Now you have to add to your new project:
> **E57Format-d.lib** from **libE57Format\build\Debug** to libraries
> **xerces-c_3D.lib** from **xerces-c\build\src\Debug** to libraries
> **xerces-c_3_2D.dll** copy to output folder
> 
> And **add all "*.h" files** from folder **libE57Format\include**
> And add include file **E57Export.h** from **libE57Format\build**

Thank you so much, I lost all day for installing xerces and finally your code works, thank you so much again.

**Comment by JamesMorDigi** [comment]
@dawiddyrcz Thanks David for outlining this installation process.

I have a small question:


When you say 
Now you have to add to your new project:
E57Format-d.lib from libE57Format\build\Debug to _libraries_
xerces-c_3D.lib from xerces-c\build\src\Debug to _libraries_
xerces-c_3_2D.dll copy to output folder

And add all "*.h" files from folder libE57Format\include
And add include file E57Export.h from libE57Format\build


Can you or @mohd-naushaaad  please specify the location of the '_libraries_' and '_output_' folder

I was able to generate the .lib and .dll files, but I don't know where to put them once generated


And again thanks for the above explanation! I have spent a very long time trying to set up this, and this seems to be the last hurdle.
