### ISSUE TITLE
Exception "Unknown error" thrown reading and writing certain files

### ISSUE THREAD

**Issue by jenskalusniak** [asmaloney/libE57Format#69]
An exception "Unknown error" is thrown, when trying to read from (or writing to) a file, which name includes mutated vowels/umlauts like ä,ö,ü. Maybe even other characters, but those are the ones I can test it with. 

This happens when I use lib57Format in our software, but the error also occurs in CloudCompare.
![grafik](https://user-images.githubusercontent.com/24593774/121482330-5bc44480-c9cd-11eb-9329-49f732bfa437.png)

OS: Windows 10 (latest)
Windows SDK: 10.0.18362.0
Compiler: Visual Studio 2019 (v142)
libE57Format Version 2.2.0

**Comment by asmaloney** [comment]
This should be handled by [this commit](https://github.com/asmaloney/libE57Format/commit/8ee8582910ee06a22b47bec0ef19841af598394d) from this [this issue](https://github.com/asmaloney/libE57Format/issues/26).

The last comment there suggests that maybe the file name being passed in from the application side isn't UTF-8. Is that a possibility?

Not totally helpful since I can't test it on Windows - and this code is Windows-specific - but files like `open me äöü.e57` work for me on macOS.

Are you sure the "Unknown error" is a result of the file name? Have you set breakpoints to see what's causing an "Unknown error"?

**Comment by dgirardeau** [comment]
In CloudCompare, we are using QSting::toStdString to pass the filemane to e57::ImageFile.

According to Qt documentation: 
> The Unicode data is converted into 8-bit characters using the toUtf8() function.

With the latest version of CC (2.12), I can successfully load files with local characters:
> F:\répertoire cheloû\manitou éééééé - Copie.e57

**Comment by jenskalusniak** [comment]
@dgirardeau:
I can confirm that it works just fine with CC 2.12alpha, but not with the latest stable version 2.11.3. Saving and opening e57 files results in an error.
![cc_error](https://user-images.githubusercontent.com/24593774/121771068-687f9e80-cb6d-11eb-9741-9fbbd6cd6ad3.png)
![cc_error_load](https://user-images.githubusercontent.com/24593774/121771084-72090680-cb6d-11eb-99b6-744644f50762.png)

Is the use of the toUtf8() function a new thing in CC 2.12?

@asmaloney:
I "undid" the changes from the commit you mentioned and it works without any errors. Also the __GNUC__ case works just fine on (my) Windows.
As for the _MSC_VER case: The conversion seems to cause an error in the Windows C Runtime Library (ucrtbase.dll) according to the Windows Event Manager.
Unfortunatly I cant access my work computer the next couple of days to do further checking.

**Comment by dgirardeau** [comment]
@jenskalusniak Yes probably. See https://github.com/CloudCompare/CloudCompare/commit/b683f43542732851678099fc57654acfdbece019

**Comment by asmaloney** [comment]
For future readers - I added tests for reading file names with umlauts & they pass.

The main thing that is not obvious is if you are including UTF-8 characters directly in a source file (as I do in the tests), you need to set the `utf-8` flag on MSVC:

```cpp
target_compile_options( testE57
	PUBLIC
		$<$<C_COMPILER_ID:MSVC>:/utf-8>
		$<$<CXX_COMPILER_ID:MSVC>:/utf-8>
)
```
