### ISSUE TITLE
how to use ? im new 

### ISSUE THREAD

**Issue by yuchuxiang** [asmaloney/libE57Format#72]
i want to read or write ,so how to reach ?someone give tutorials?thanks,

**Comment by asmaloney** [comment]
The docs are old and someone needs to go over them and update them, but they [are online here](https://asmaloney.github.io/libE57Format-docs/index.html). There are no tutorials available.

Probably the easiest way to get started would be by using the [e57::Reader](https://asmaloney.github.io/libE57Format-docs/classe57_1_1_reader.html) and [e57::Writer](https://asmaloney.github.io/libE57Format-docs/classe57_1_1_writer.html)  classes (found in the [E57SimpleReader.h](https://github.com/asmaloney/libE57Format/blob/master/include/E57SimpleReader.h) and [E57SimpleWriter.h](https://github.com/asmaloney/libE57Format/blob/master/include/E57SimpleWriter.h) headers). These abstract away a lot of the details. Once you have that working then you can dig into the other stuff if you need to.

**Comment by yuchuxiang** [comment]
> 
> 
> The docs are old and someone needs to go over them and update them, but they [are online here](https://asmaloney.github.io/libE57Format-docs/index.html). There are no tutorials available.
> 
> Probably the easiest way to get started would be by using the [e57::Reader](https://asmaloney.github.io/libE57Format-docs/classe57_1_1_reader.html) and [e57::Writer](https://asmaloney.github.io/libE57Format-docs/classe57_1_1_writer.html) classes (found in the [E57SimpleReader.h](https://github.com/asmaloney/libE57Format/blob/master/include/E57SimpleReader.h) and [E57SimpleWriter.h](https://github.com/asmaloney/libE57Format/blob/master/include/E57SimpleWriter.h) headers). These abstract away a lot of the details. Once you have that working then you can dig into the other stuff if you need to.

**Comment by yuchuxiang** [comment]
@asmaloney thank you
